### ISSUE TITLE
YOLOv8_Seg.py 执行报错 TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by testwen00** [D-Robotics/rdk_model_zoo#53]
Traceback (most recent call last):
  File "YOLOv8_Seg.py", line 85, in <module>
    class BaseModel:
  File "YOLOv8_Seg.py", line 176, in BaseModel
    def forward(self, input_tensor: np.array) -> list[dnn.pyDNNTensor]:
TypeError: 'type' object is not subscriptable

Python 3.8.10
cat /etc/version
2.0.0

**Comment by testwen00** [comment]
好像x3是不能运行，python版本要3.10

**Comment by WuChao-2024** [comment]
只需要将每个函数的定义改成最原始的状态即可，或者类似from type import * 这样，导入一些Python3.8需要导入的库
